# Wifi Configuration
SSID = "YOUR_SSID"
SSID_PW = "YOUR_WIFI_PASSWORD"
GATEWAY = 'YOUR_WIFI_GATEWAY'
SUBNET = '255.255.255.0'
STATIC_IP = 'STATIC_IP_OF_WIPY'
DNS_SERVER = 'YOUR_DNS_SERVER'

# Losant Configuration
LOSANT_DEVICE_ID = ''
LOSANT_API_KEY = ''
LOSANT_API_SECRET = ''

# Device configuration
VREF_ACTUAL_IN_MILLIAMPS = 1100 # This value is measured manually and set.
UPDATE_INTERVAL_IN_SEC = 10
THERM_BETA = 4660.0
THERM_NOMINAL_TEMP = 25.0
THERM_NOMINAL_RES = 1000000.0
SERIES_RESISTOR_1 = 9840.0
SERIES_RESISTOR_2 = 9830.0
OVEN_THERM_ADC_PIN = 'P13'
FOOD_THERM_ADC_PIN = 'P14'
STATUS_LED_PIN = 'G16'
